micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost:50051}:${KEY_MANAGER_PORT:50051}'
      plaintext: true
      max-retry-attempts: 10

