micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false

metrics:
  enabled: true

endpoints:
  all.path: /actuator
  beans:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  prometheus:
      enabled: true
      sensitive: false